name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    environment: lucas-fish-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          connection_string: ${{ secrets.AZURE_BLOB_CONNECTION_STRING }}
          container_name: "$web"
          source_dir: build
          sync: false
