name: Deploy

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: ${{ 14.x }}
      - run: npm ci
      - run: npm run build
      - uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        name: Deploying build
        with:
          connection_string: ${{ secrets.YourAzureBlobConnectionString }}
          container_name: aoelucasfish
          source_folder: dist
